[tool.poetry]
name = "twitter-topic"
version = "0.1.0"
description = ""
authors = ["hjmr <2620990+hjmr@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
twitterapi = "^2.5.11"
gensim = "^3.8.3"
matplotlib = "^3.2.1"
pyLDAvis = "^2.1.2"
numpy = "^1.18.5"
wordcloud = "^1.7.0"
Pillow = "^7.1.2"
scikit-learn = "^0.23.1"
mecab = "^0.996.2"

[tool.poetry.dev-dependencies]
pylint = "^2.5.2"
autopep8 = "^1.5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
